export interface Figure {
  id: string;
  name: string;
  /** 别名/异名/常见称呼，用于归一化输入 */
  aliases: string[];
  /** 朝代，如"隋""唐" */
  dynasty: string;
  /** 身份/角色标签，如"皇帝""开国君主""名将""诗人" */
  roles: string[];
  /** 主题标签（事件/群体/流派），用于计算特征重叠 */
  tags: string[];
  /** 与其他人物的显式关系：key 为对方 id，value 为关系描述 */
  relations: Record<string, string>;
}

export const FIGURES: Figure[] = [
  // ===== 先秦 =====
  {
    id: "kongzi",
    name: "孔子",
    aliases: ["孔丘", "仲尼", "至圣先师"],
    dynasty: "春秋",
    roles: ["思想家", "教育家"],
    tags: ["儒家", "诸子百家", "论语"],
    relations: { mengzi: "儒家先师后学，并称孔孟", laozi: "问礼于老子" },
  },
  {
    id: "laozi",
    name: "老子",
    aliases: ["李耳", "老聃"],
    dynasty: "春秋",
    roles: ["思想家"],
    tags: ["道家", "诸子百家", "道德经"],
    relations: { zhuangzi: "道家宗师，并称老庄", kongzi: "孔子曾问礼" },
  },
  {
    id: "mengzi",
    name: "孟子",
    aliases: ["孟轲", "亚圣"],
    dynasty: "战国",
    roles: ["思想家"],
    tags: ["儒家", "诸子百家"],
    relations: { kongzi: "私淑孔子，并称孔孟" },
  },
  {
    id: "zhuangzi",
    name: "庄子",
    aliases: ["庄周"],
    dynasty: "战国",
    roles: ["思想家"],
    tags: ["道家", "诸子百家", "逍遥游"],
    relations: { laozi: "承老子之学，并称老庄" },
  },
  {
    id: "sunzi",
    name: "孙武",
    aliases: ["孙子", "兵圣"],
    dynasty: "春秋",
    roles: ["军事家"],
    tags: ["兵家", "孙子兵法"],
    relations: {},
  },
  {
    id: "qushi",
    name: "屈原",
    aliases: ["屈平", "灵均"],
    dynasty: "战国",
    roles: ["诗人", "政治家"],
    tags: ["楚辞", "离骚", "端午"],
    relations: {},
  },
  {
    id: "qinshihuang",
    name: "秦始皇",
    aliases: ["嬴政", "始皇帝"],
    dynasty: "秦",
    roles: ["皇帝", "开国君主"],
    tags: ["统一六国", "郡县制", "长城", "焚书坑儒"],
    relations: { lisi: "君臣，共定秦制", huhai: "父子，传位之争" },
  },
  {
    id: "lisi",
    name: "李斯",
    aliases: ["李斯"],
    dynasty: "秦",
    roles: ["名臣", "丞相"],
    tags: ["统一六国", "郡县制", "法家", "焚书坑儒"],
    relations: { qinshihuang: "君臣，共定秦制", zhaogao: "同朝，为赵高所害" },
  },
  {
    id: "zhaogao",
    name: "赵高",
    aliases: ["赵高"],
    dynasty: "秦",
    roles: ["宦官", "权臣"],
    tags: ["指鹿为马", "沙丘之变"],
    relations: { lisi: "同朝，构陷李斯", huhai: "拥立胡亥" },
  },
  {
    id: "huhai",
    name: "胡亥",
    aliases: ["秦二世"],
    dynasty: "秦",
    roles: ["皇帝"],
    tags: ["沙丘之变", "亡国之君"],
    relations: { qinshihuang: "父子", zhaogao: "为赵高所控" },
  },

  // ===== 秦末楚汉 / 西汉 =====
  {
    id: "xiangyu",
    name: "项羽",
    aliases: ["项籍", "西楚霸王"],
    dynasty: "秦末",
    roles: ["名将", "诸侯"],
    tags: ["楚汉相争", "巨鹿之战", "鸿门宴", "垓下"],
    relations: { liubang: "楚汉相争，生死对手", yuji: "霸王别姬" },
  },
  {
    id: "liubang",
    name: "刘邦",
    aliases: ["汉高祖", "刘季"],
    dynasty: "汉",
    roles: ["皇帝", "开国君主"],
    tags: ["楚汉相争", "鸿门宴", "汉初"],
    relations: {
      xiangyu: "楚汉相争，生死对手",
      hanxin: "君臣，成也萧何",
      xiaohe: "君臣，汉初三杰",
      zhangliang: "君臣，汉初三杰",
    },
  },
  {
    id: "hanxin",
    name: "韩信",
    aliases: ["淮阴侯", "兵仙"],
    dynasty: "汉",
    roles: ["名将"],
    tags: ["楚汉相争", "汉初三杰", "背水一战", "胯下之辱"],
    relations: { liubang: "君臣", xiaohe: "成也萧何败也萧何", zhangliang: "汉初三杰" },
  },
  {
    id: "xiaohe",
    name: "萧何",
    aliases: ["萧何", "酂侯"],
    dynasty: "汉",
    roles: ["名臣", "丞相"],
    tags: ["汉初三杰", "汉初"],
    relations: { liubang: "君臣", hanxin: "月下追韩信", zhangliang: "汉初三杰" },
  },
  {
    id: "zhangliang",
    name: "张良",
    aliases: ["子房", "留侯"],
    dynasty: "汉",
    roles: ["谋士"],
    tags: ["汉初三杰", "运筹帷幄"],
    relations: { liubang: "君臣", hanxin: "汉初三杰", xiaohe: "汉初三杰" },
  },
  {
    id: "hanwudi",
    name: "汉武帝",
    aliases: ["刘彻"],
    dynasty: "汉",
    roles: ["皇帝"],
    tags: ["罢黜百家", "北击匈奴", "丝绸之路"],
    relations: { weiqing: "君臣", huoqubing: "君臣", zhangqian: "遣使西域", simaqian: "同朝" },
  },
  {
    id: "weiqing",
    name: "卫青",
    aliases: ["卫青", "长平侯"],
    dynasty: "汉",
    roles: ["名将"],
    tags: ["北击匈奴", "漠北之战"],
    relations: { hanwudi: "君臣", huoqubing: "舅甥名将" },
  },
  {
    id: "huoqubing",
    name: "霍去病",
    aliases: ["霍去病", "冠军侯"],
    dynasty: "汉",
    roles: ["名将"],
    tags: ["北击匈奴", "封狼居胥"],
    relations: { hanwudi: "君臣", weiqing: "舅甥名将" },
  },
  {
    id: "zhangqian",
    name: "张骞",
    aliases: ["张骞", "博望侯"],
    dynasty: "汉",
    roles: ["外交家", "探险家"],
    tags: ["丝绸之路", "凿空西域"],
    relations: { hanwudi: "奉命出使" },
  },
  {
    id: "simaqian",
    name: "司马迁",
    aliases: ["太史公", "子长"],
    dynasty: "汉",
    roles: ["史学家"],
    tags: ["史记", "太史令"],
    relations: { hanwudi: "同朝" },
  },
  {
    id: "wangzhaojun",
    name: "王昭君",
    aliases: ["昭君", "王嫱"],
    dynasty: "汉",
    roles: ["和亲女子"],
    tags: ["昭君出塞", "四大美女", "北击匈奴"],
    relations: {},
  },

  // ===== 三国 =====
  {
    id: "caocao",
    name: "曹操",
    aliases: ["孟德", "魏武帝"],
    dynasty: "三国",
    roles: ["政治家", "军事家", "诗人"],
    tags: ["赤壁之战", "官渡之战", "挟天子", "建安文学"],
    relations: {
      liubei: "三国鼎立对手",
      sunquan: "赤壁对手",
      zhugeliang: "宿敌",
      guanyu: "爱才而不能用",
      caozhi: "父子",
    },
  },
  {
    id: "liubei",
    name: "刘备",
    aliases: ["玄德", "汉昭烈帝"],
    dynasty: "三国",
    roles: ["皇帝", "开国君主"],
    tags: ["桃园结义", "三顾茅庐", "赤壁之战", "蜀汉"],
    relations: {
      guanyu: "桃园结义，义结金兰",
      zhangfei: "桃园结义，义结金兰",
      zhugeliang: "君臣，三顾茅庐",
      caocao: "三国鼎立对手",
      sunquan: "孙刘联盟",
    },
  },
  {
    id: "guanyu",
    name: "关羽",
    aliases: ["云长", "关公", "武圣"],
    dynasty: "三国",
    roles: ["名将"],
    tags: ["桃园结义", "过五关斩六将", "蜀汉", "水淹七军"],
    relations: {
      liubei: "桃园结义",
      zhangfei: "桃园结义",
      caocao: "降汉不降曹",
    },
  },
  {
    id: "zhangfei",
    name: "张飞",
    aliases: ["翼德"],
    dynasty: "三国",
    roles: ["名将"],
    tags: ["桃园结义", "长坂坡", "蜀汉"],
    relations: { liubei: "桃园结义", guanyu: "桃园结义" },
  },
  {
    id: "zhugeliang",
    name: "诸葛亮",
    aliases: ["孔明", "卧龙", "武侯"],
    dynasty: "三国",
    roles: ["政治家", "军事家"],
    tags: ["三顾茅庐", "赤壁之战", "出师表", "六出祁山", "蜀汉"],
    relations: {
      liubei: "君臣，三顾茅庐",
      caocao: "宿敌",
      zhouyu: "既生瑜何生亮",
      simayi: "北伐宿敌",
    },
  },
  {
    id: "sunquan",
    name: "孙权",
    aliases: ["仲谋", "吴大帝"],
    dynasty: "三国",
    roles: ["皇帝", "开国君主"],
    tags: ["赤壁之战", "东吴", "孙刘联盟"],
    relations: { liubei: "孙刘联盟", caocao: "赤壁对手", zhouyu: "君臣" },
  },
  {
    id: "zhouyu",
    name: "周瑜",
    aliases: ["公瑾"],
    dynasty: "三国",
    roles: ["名将", "军事家"],
    tags: ["赤壁之战", "东吴", "火烧赤壁"],
    relations: { sunquan: "君臣", zhugeliang: "既生瑜何生亮" },
  },
  {
    id: "simayi",
    name: "司马懿",
    aliases: ["仲达"],
    dynasty: "三国",
    roles: ["政治家", "军事家"],
    tags: ["六出祁山", "曹魏", "空城计"],
    relations: { zhugeliang: "北伐宿敌", caocao: "魏之重臣" },
  },
  {
    id: "caozhi",
    name: "曹植",
    aliases: ["子建", "陈思王"],
    dynasty: "三国",
    roles: ["诗人"],
    tags: ["建安文学", "七步诗", "洛神赋"],
    relations: { caocao: "父子", caopi: "兄弟，七步成诗" },
  },
  {
    id: "caopi",
    name: "曹丕",
    aliases: ["子桓", "魏文帝"],
    dynasty: "三国",
    roles: ["皇帝"],
    tags: ["建安文学", "曹魏", "篡汉"],
    relations: { caocao: "父子", caozhi: "兄弟，七步逼诗" },
  },

  // ===== 隋唐 =====
  {
    id: "yangjian",
    name: "杨坚",
    aliases: ["隋文帝"],
    dynasty: "隋",
    roles: ["皇帝", "开国君主"],
    tags: ["统一南北", "开皇之治", "杨氏"],
    relations: { yangguang: "父子，一始一终定隋祚", liyuan: "君臣旧识" },
  },
  {
    id: "yangguang",
    name: "隋炀帝",
    aliases: ["杨广"],
    dynasty: "隋",
    roles: ["皇帝"],
    tags: ["大运河", "亡国之君", "杨氏"],
    relations: { yangjian: "父子", liyuan: "表亲，唐代隋" },
  },
  {
    id: "liyuan",
    name: "李渊",
    aliases: ["唐高祖"],
    dynasty: "唐",
    roles: ["皇帝", "开国君主"],
    tags: ["太原起兵", "李唐"],
    relations: { lishimin: "父子", lijiancheng: "父子", liyuanji: "父子" },
  },
  {
    id: "lishimin",
    name: "李世民",
    aliases: ["唐太宗", "天策上将"],
    dynasty: "唐",
    roles: ["皇帝"],
    tags: ["玄武门之变", "贞观之治", "凌烟阁", "李唐"],
    relations: {
      liyuan: "父子",
      lijiancheng: "兄弟，玄武门对手",
      liyuanji: "兄弟，玄武门对手",
      weizheng: "君臣，凌烟阁明镜",
      yuchijingde: "君臣，凌烟阁功臣",
      qinqiong: "君臣，凌烟阁功臣",
      wuzetian: "曾纳为才人",
    },
  },
  {
    id: "lijiancheng",
    name: "李建成",
    aliases: ["隐太子"],
    dynasty: "唐",
    roles: ["太子"],
    tags: ["玄武门之变", "李唐"],
    relations: { liyuan: "父子", lishimin: "兄弟，玄武门对手", liyuanji: "同谋" },
  },
  {
    id: "liyuanji",
    name: "李元吉",
    aliases: ["齐王"],
    dynasty: "唐",
    roles: ["王"],
    tags: ["玄武门之变", "李唐"],
    relations: { liyuan: "父子", lishimin: "兄弟，玄武门对手", lijiancheng: "同谋" },
  },
  {
    id: "weizheng",
    name: "魏征",
    aliases: ["魏徵", "魏郑公"],
    dynasty: "唐",
    roles: ["名臣", "谏臣"],
    tags: ["凌烟阁", "贞观之治", "李唐"],
    relations: { lishimin: "君臣，凌烟阁明镜", lijiancheng: "旧事太子" },
  },
  {
    id: "yuchijingde",
    name: "尉迟敬德",
    aliases: ["尉迟恭", "鄂国公"],
    dynasty: "唐",
    roles: ["名将"],
    tags: ["凌烟阁", "玄武门之变", "门神", "李唐"],
    relations: { lishimin: "君臣，凌烟阁功臣", qinqiong: "同列门神" },
  },
  {
    id: "qinqiong",
    name: "秦琼",
    aliases: ["秦叔宝", "胡国公"],
    dynasty: "唐",
    roles: ["名将"],
    tags: ["凌烟阁", "门神", "李唐"],
    relations: { lishimin: "君臣，凌烟阁功臣", yuchijingde: "同列门神" },
  },
  {
    id: "wuzetian",
    name: "武则天",
    aliases: ["武曌", "则天大圣皇帝"],
    dynasty: "唐",
    roles: ["皇帝", "女皇"],
    tags: ["武周", "女皇", "李唐"],
    relations: { lishimin: "曾为才人", digrenjie: "君臣" },
  },
  {
    id: "digrenjie",
    name: "狄仁杰",
    aliases: ["狄公", "狄梁公"],
    dynasty: "唐",
    roles: ["名臣"],
    tags: ["武周", "神探"],
    relations: { wuzetian: "君臣" },
  },
  {
    id: "libai",
    name: "李白",
    aliases: ["李太白", "青莲居士", "诗仙"],
    dynasty: "唐",
    roles: ["诗人"],
    tags: ["盛唐", "浪漫主义", "诗仙"],
    relations: { dufu: "李杜并称", hezhizhang: "忘年之交" },
  },
  {
    id: "dufu",
    name: "杜甫",
    aliases: ["杜子美", "少陵野老", "诗圣"],
    dynasty: "唐",
    roles: ["诗人"],
    tags: ["盛唐", "现实主义", "诗圣", "三吏三别"],
    relations: { libai: "李杜并称", baijuyi: "现实主义先声" },
  },
  {
    id: "baijuyi",
    name: "白居易",
    aliases: ["乐天", "香山居士"],
    dynasty: "唐",
    roles: ["诗人"],
    tags: ["中唐", "新乐府", "长恨歌", "琵琶行"],
    relations: { dufu: "承现实主义", yuanzhen: "元白唱和" },
  },
  {
    id: "wangwei",
    name: "王维",
    aliases: ["摩诘", "诗佛"],
    dynasty: "唐",
    roles: ["诗人", "画家"],
    tags: ["盛唐", "山水田园", "诗佛"],
    relations: { libai: "同时盛唐" },
  },
  {
    id: "hezhizhang",
    name: "贺知章",
    aliases: ["贺知章", "四明狂客"],
    dynasty: "唐",
    roles: ["诗人"],
    tags: ["盛唐", "咏柳"],
    relations: { libai: "金龟换酒，忘年交" },
  },
  {
    id: "yuanzhen",
    name: "元稹",
    aliases: ["微之"],
    dynasty: "唐",
    roles: ["诗人"],
    tags: ["中唐", "新乐府"],
    relations: { baijuyi: "元白唱和" },
  },
  {
    id: "hanyu",
    name: "韩愈",
    aliases: ["退之", "昌黎先生"],
    dynasty: "唐",
    roles: ["文学家"],
    tags: ["唐宋八大家", "古文运动", "中唐"],
    relations: { liuzongyuan: "古文运动，韩柳并称" },
  },
  {
    id: "liuzongyuan",
    name: "柳宗元",
    aliases: ["子厚", "柳河东"],
    dynasty: "唐",
    roles: ["文学家"],
    tags: ["唐宋八大家", "古文运动", "中唐"],
    relations: { hanyu: "古文运动，韩柳并称" },
  },
  {
    id: "yangguifei",
    name: "杨贵妃",
    aliases: ["杨玉环", "太真"],
    dynasty: "唐",
    roles: ["贵妃"],
    tags: ["四大美女", "安史之乱", "长恨歌", "马嵬坡"],
    relations: { tangxuanzong: "帝妃，长恨歌" },
  },
  {
    id: "tangxuanzong",
    name: "唐玄宗",
    aliases: ["李隆基", "唐明皇"],
    dynasty: "唐",
    roles: ["皇帝"],
    tags: ["开元盛世", "安史之乱", "马嵬坡"],
    relations: { yangguifei: "帝妃", anlushan: "安史之乱" },
  },
  {
    id: "anlushan",
    name: "安禄山",
    aliases: ["安禄山"],
    dynasty: "唐",
    roles: ["叛将"],
    tags: ["安史之乱"],
    relations: { tangxuanzong: "起兵反唐" },
  },

  // ===== 宋 =====
  {
    id: "zhaokuangyin",
    name: "赵匡胤",
    aliases: ["宋太祖"],
    dynasty: "宋",
    roles: ["皇帝", "开国君主"],
    tags: ["陈桥兵变", "杯酒释兵权", "赵宋"],
    relations: {},
  },
  {
    id: "yuefei",
    name: "岳飞",
    aliases: ["鹏举", "岳武穆"],
    dynasty: "宋",
    roles: ["名将"],
    tags: ["抗金", "精忠报国", "莫须有", "靖康"],
    relations: { qinhui: "为秦桧所害", songgaozong: "君臣，十二金牌" },
  },
  {
    id: "qinhui",
    name: "秦桧",
    aliases: ["秦桧"],
    dynasty: "宋",
    roles: ["权臣"],
    tags: ["抗金", "莫须有", "奸臣"],
    relations: { yuefei: "构陷岳飞", songgaozong: "君臣" },
  },
  {
    id: "songgaozong",
    name: "宋高宗",
    aliases: ["赵构"],
    dynasty: "宋",
    roles: ["皇帝"],
    tags: ["南宋", "靖康", "抗金"],
    relations: { yuefei: "十二金牌召回", qinhui: "重用秦桧" },
  },
  {
    id: "sushi",
    name: "苏轼",
    aliases: ["东坡居士", "苏东坡", "子瞻"],
    dynasty: "宋",
    roles: ["文学家", "诗人"],
    tags: ["唐宋八大家", "豪放派", "三苏"],
    relations: { suxun: "父子，三苏", suzhe: "兄弟，三苏", ouyangxiu: "门生", wanganshi: "变法政敌" },
  },
  {
    id: "suxun",
    name: "苏洵",
    aliases: ["明允", "老泉"],
    dynasty: "宋",
    roles: ["文学家"],
    tags: ["唐宋八大家", "三苏"],
    relations: { sushi: "父子，三苏", suzhe: "父子，三苏" },
  },
  {
    id: "suzhe",
    name: "苏辙",
    aliases: ["子由"],
    dynasty: "宋",
    roles: ["文学家"],
    tags: ["唐宋八大家", "三苏"],
    relations: { sushi: "兄弟，三苏", suxun: "父子，三苏" },
  },
  {
    id: "ouyangxiu",
    name: "欧阳修",
    aliases: ["醉翁", "六一居士"],
    dynasty: "宋",
    roles: ["文学家"],
    tags: ["唐宋八大家", "醉翁亭记"],
    relations: { sushi: "提携后进", wanganshi: "同朝" },
  },
  {
    id: "wanganshi",
    name: "王安石",
    aliases: ["介甫", "半山"],
    dynasty: "宋",
    roles: ["政治家", "文学家"],
    tags: ["唐宋八大家", "熙宁变法"],
    relations: { sushi: "变法政敌", simaguang: "变法政敌", ouyangxiu: "同朝" },
  },
  {
    id: "simaguang",
    name: "司马光",
    aliases: ["君实", "涑水先生"],
    dynasty: "宋",
    roles: ["史学家", "政治家"],
    tags: ["资治通鉴", "反变法", "砸缸"],
    relations: { wanganshi: "变法政敌" },
  },
  {
    id: "liqingzhao",
    name: "李清照",
    aliases: ["易安居士"],
    dynasty: "宋",
    roles: ["词人"],
    tags: ["婉约派", "宋词", "靖康"],
    relations: { xinqiji: "婉约豪放，济南二安" },
  },
  {
    id: "xinqiji",
    name: "辛弃疾",
    aliases: ["幼安", "稼轩"],
    dynasty: "宋",
    roles: ["词人", "将领"],
    tags: ["豪放派", "宋词", "抗金"],
    relations: { liqingzhao: "济南二安", sushi: "豪放并称苏辛" },
  },
  {
    id: "baozheng",
    name: "包拯",
    aliases: ["包青天", "包公"],
    dynasty: "宋",
    roles: ["名臣"],
    tags: ["清官", "开封府"],
    relations: {},
  },
  {
    id: "wentianxiang",
    name: "文天祥",
    aliases: ["文山", "宋瑞"],
    dynasty: "宋",
    roles: ["名臣", "将领"],
    tags: ["抗元", "正气歌", "过零丁洋", "南宋"],
    relations: {},
  },

  // ===== 元明清 =====
  {
    id: "chengjisihan",
    name: "成吉思汗",
    aliases: ["铁木真", "元太祖"],
    dynasty: "元",
    roles: ["可汗", "军事家"],
    tags: ["蒙古", "西征", "开国君主"],
    relations: { hubilie: "祖孙，蒙元" },
  },
  {
    id: "hubilie",
    name: "忽必烈",
    aliases: ["元世祖"],
    dynasty: "元",
    roles: ["皇帝", "可汗"],
    tags: ["蒙古", "元朝", "灭南宋"],
    relations: { chengjisihan: "祖孙，蒙元" },
  },
  {
    id: "zhuyuanzhang",
    name: "朱元璋",
    aliases: ["明太祖", "洪武帝"],
    dynasty: "明",
    roles: ["皇帝", "开国君主"],
    tags: ["布衣天子", "大明", "废丞相"],
    relations: { zhudi: "父子", liubowen: "君臣" },
  },
  {
    id: "zhudi",
    name: "朱棣",
    aliases: ["明成祖", "永乐帝"],
    dynasty: "明",
    roles: ["皇帝"],
    tags: ["靖难之役", "大明", "迁都北京", "永乐大典"],
    relations: { zhuyuanzhang: "父子", zhengHe: "遣其下西洋" },
  },
  {
    id: "liubowen",
    name: "刘伯温",
    aliases: ["刘基", "青田先生"],
    dynasty: "明",
    roles: ["谋士"],
    tags: ["大明", "开国谋臣"],
    relations: { zhuyuanzhang: "君臣" },
  },
  {
    id: "zhengHe",
    name: "郑和",
    aliases: ["三保太监", "马三宝"],
    dynasty: "明",
    roles: ["航海家", "宦官"],
    tags: ["七下西洋", "大明"],
    relations: { zhudi: "奉命下西洋" },
  },
  {
    id: "haikui",
    name: "海瑞",
    aliases: ["海刚峰"],
    dynasty: "明",
    roles: ["名臣"],
    tags: ["清官", "大明", "抬棺上疏"],
    relations: {},
  },
  {
    id: "qijiguang",
    name: "戚继光",
    aliases: ["戚少保", "元敬"],
    dynasty: "明",
    roles: ["名将"],
    tags: ["抗倭", "戚家军", "大明"],
    relations: {},
  },
  {
    id: "kangxi",
    name: "康熙",
    aliases: ["玄烨", "康熙帝"],
    dynasty: "清",
    roles: ["皇帝"],
    tags: ["康乾盛世", "擒鳌拜", "平三藩", "大清"],
    relations: { yongzheng: "父子", qianlong: "祖孙" },
  },
  {
    id: "yongzheng",
    name: "雍正",
    aliases: ["胤禛", "雍正帝"],
    dynasty: "清",
    roles: ["皇帝"],
    tags: ["九子夺嫡", "军机处", "大清"],
    relations: { kangxi: "父子", qianlong: "父子" },
  },
  {
    id: "qianlong",
    name: "乾隆",
    aliases: ["弘历", "乾隆帝"],
    dynasty: "清",
    roles: ["皇帝"],
    tags: ["康乾盛世", "十全老人", "大清"],
    relations: { yongzheng: "父子", kangxi: "祖孙", heshen: "君臣" },
  },
  {
    id: "heshen",
    name: "和珅",
    aliases: ["和珅"],
    dynasty: "清",
    roles: ["权臣"],
    tags: ["巨贪", "大清"],
    relations: { qianlong: "君臣宠信" },
  },
  {
    id: "linzexu",
    name: "林则徐",
    aliases: ["林文忠", "少穆"],
    dynasty: "清",
    roles: ["名臣"],
    tags: ["虎门销烟", "鸦片战争", "晚清"],
    relations: {},
  },
  {
    id: "zengguofan",
    name: "曾国藩",
    aliases: ["曾文正", "涤生"],
    dynasty: "清",
    roles: ["名臣", "将领"],
    tags: ["湘军", "洋务运动", "晚清", "平太平天国"],
    relations: { lihongzhang: "师生，同办洋务" },
  },
  {
    id: "lihongzhang",
    name: "李鸿章",
    aliases: ["李中堂", "少荃"],
    dynasty: "清",
    roles: ["名臣"],
    tags: ["淮军", "洋务运动", "晚清", "北洋"],
    relations: { zengguofan: "师生", cixi: "君臣" },
  },
  {
    id: "cixi",
    name: "慈禧",
    aliases: ["慈禧太后", "西太后"],
    dynasty: "清",
    roles: ["太后"],
    tags: ["晚清", "垂帘听政"],
    relations: { lihongzhang: "倚重李鸿章" },
  },

  // ===== 演义/传说（低关联兜底趣味项）=====
  {
    id: "liyuanba",
    name: "李元霸",
    aliases: ["李元霸"],
    dynasty: "隋唐演义",
    roles: ["虚构猛将"],
    tags: ["演义", "李唐"],
    relations: {},
  },
];

const NORM = (s: string) => s.trim().replace(/\s+/g, "").toLowerCase();

const LOOKUP = new Map<string, Figure>();
for (const f of FIGURES) {
  LOOKUP.set(NORM(f.name), f);
  for (const a of f.aliases) LOOKUP.set(NORM(a), f);
}

export function findFigure(input: string): Figure | undefined {
  return LOOKUP.get(NORM(input));
}

export function getFigure(id: string): Figure | undefined {
  return FIGURES.find((f) => f.id === id);
}

export { NORM as normalizeName };
